stages:
  - test
  - release
  - deploy
  - cleanup

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == 'web'

include:
  - project: cicd/template-ci
    ref: master
    file: .rules_deploy.yml
  - project: cicd/template-ci
    ref: master
    file: .rules_def.yml


Tests and Lint:
  stage: test
  rules:
     - !reference [.rules_def, test]
  trigger:
    include:
      - project: cicd/template-ci
        ref: master
        file: tests.yml
    strategy: depend

Release:
  stage: release
  rules:
     - !reference [.rules_def, release]
  trigger:
    include:
      - project: cicd/template-ci
        ref: master
        file: release-nyx.yml
    strategy: depend

Deploy:
  stage: deploy
  rules:
   - !reference [.rules_deploy, deploy]
  trigger:
    include:
      - project: cicd/template-ci
        ref: master
        file: werf_converge.yml

Review:
  stage: deploy
  needs:
    - Release
  rules: 
    - !reference [.rules_def, review]
  trigger:
    include:
      - project: cicd/template-ci
        ref: master
        file: review.yml
    strategy: depend

Cleanup:
  stage: cleanup
  only: [schedules]
  trigger:
    include:
      - project: cicd/template-ci
        ref: master
        file: werf_cleanup.yml
